all_joints:
- - 0
- - 1
all_joints_names:
- Pbsc0
- Pbsc1
batch_size: 1
bottomheight: 400
crop: true
cropratio: 0.4
dataset: training-datasets/iteration-3/UnaugmentedDataSet_PERMar18/PER_CLC95shuffle1.mat
dataset_type: default
display_iters: 1000
global_scale: 0.8
init_weights: /Users/clc/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets/iteration-3/UnaugmentedDataSet_PERMar18/Documentation_data-PER_95shuffle1.pickle
min_input_size: 64
minsize: 100
mirror: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 2
pos_dist_thresh: 17
project_path: /Users/clc/Documents/EPFL/NeLy/Data/ANproj/dlc/PER-CLC-2020-03-18
rightwidth: 400
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
topheight: 400
